# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-17 20:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 17, 20, 15, 30, 246266, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='station',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 17, 20, 15, 30, 246303, tzinfo=utc)),
        ),
    ]
